services:
  mongo:
    image: mongo:6
    container_name: mongo-dev
    ports: ["27017:27017"]
    volumes: ["mongo-data-dev:/data/db"]
    restart: unless-stopped
    networks:
      - chadnet

  mongo-express:
    image: mongo-express:1
    container_name: mongo-express-dev
    ports: ["28081:8081"]
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=secret
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - chadnet

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: backend
    container_name: chad-backend-dev
    ports: ["5000:5000"]
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=hospital_dev
      - SEED_ON_START=true
      - FLASK_DEBUG=1
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - chadnet

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: frontend
    container_name: chad-frontend-dev
    ports: ["25173:5173"]
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - chadnet

volumes:
  mongo-data-dev:

networks:
  chadnet:
    driver: bridge